# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Comment the following line to switch to the mainstream AudioKit pod
source 'https://github.com/AudioKit/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

project 'SamplerDemo.xcodeproj'

target 'SamplerDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SamplerDemo
  pod 'AudioKit', '>=4.5.5.b1'
end
